# Generated by Django 5.1.6 on 2025-03-13 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='book_img',
            field=models.FileField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='username',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='wallet_balance',
            field=models.FloatField(default=1000),
        ),
        migrations.AlterModelTable(
            name='booktransferhistory',
            table='book_transfer_history',
        ),
        migrations.AlterModelTable(
            name='userbookstatus',
            table='user_book_status',
        ),
        migrations.DeleteModel(
            name='UserBookDetails',
        ),
    ]
