# Generated by Django 5.1.6 on 2025-03-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0004_remove_bookdetails_user_alter_bookdetails_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='book_img',
            field=models.FileField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='created_by',
            field=models.CharField(max_length=50),
        ),
    ]
