# Generated by Django 5.1.6 on 2025-03-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0005_alter_bookdetails_book_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='created_at',
            field=models.CharField(max_length=40),
        ),
    ]
