# Generated by Django 5.1.6 on 2025-03-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0006_alter_bookdetails_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
