# Generated by Django 5.1.6 on 2025-03-18 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0007_alter_bookdetails_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='wallet_balance',
            field=models.FloatField(default=5000),
        ),
        migrations.AlterModelTable(
            name='booktransferhistory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userbookstatus',
            table=None,
        ),
        migrations.CreateModel(
            name='UserBookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.studentdetails')),
            ],
        ),
    ]
